CREATE TABLE repos (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(100),
url VARCHAR(100),
statut VARCHAR(50)
);

CREATE TABLE commentaires (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
commentaire VARCHAR(255),
repo INT NOT NULL,
FOREIGN KEY (repo) REFERENCES repos(id)
);

CREATE TABLE langages (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
langage VARCHAR(100)
);

CREATE TABLE utilise (
repo INT NOT NULL,
langage INT NOT NULL,
FOREIGN KEY (repo) REFERENCES repos(id),
FOREIGN KEY (langage) REFERENCES langages(id)
);