services:
  db:
    image: postgres
    env_file: .env
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - 8080:8080
    container_name: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy

  api:
    build: ./api
    ports:
      - 4601:4601
    command: npm run full
    restart: always
    env_file: .env
    volumes:
      - ./api:/app/
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ./client
    command: npm run dev
    restart: always
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://localhost:4601
    volumes:
      - ./client:/app/
